SetRecord: Removed uploading using signed URL
apify/apify-client-js pull request #159
Opened 2021-02-15 16:51 UTC by drobnikj

2021-02-16 13:55 UTC, mnmkng requested changes
Looks good. Just a tiny nitpick.

2021-02-16 13:55 UTC, mnmkng commented on src/utils.js
> +    if (value == null) return null;
Please use `return` or `return undefined`. I don't think we return `null` anywhere in the client.

2021-02-16 15:10 UTC, mtrunkat approved these changes

2021-02-17 18:54 UTC, mnmkng approved these changes

2021-02-19 11:18 UTC, merged