Feature/run storages
apify/apify-client-js pull request #176
Opened 2021-06-15 08:39 UTC by nguyeda1

Run storages are available via `/v2/actor-runs/{runId}/{key-value-store | log | request-queue | dataset}` .. see https://docs.apify.com/api/v2#/reference/actor-runs/run-object-and-its-storages

2021-06-15 14:29 UTC, mnmkng approved these changes
Ok, now I'm a bit torn. I thought you would need to add some code, but I scrolled down and it seems that you only added docs and the code was already there. So I guess you can ignore my comments about the version 1.3.0... 🤷‍♂️

2021-06-15 14:29 UTC, mnmkng commented on CHANGELOG.md
> +- Enabled access to actor run storages via `RunClient`
Should be a minor version bump to `1.3.0`, since features were added.

2021-06-15 14:29 UTC, mnmkng commented on package.json
> +    "version": "1.2.5",
dtto

2021-06-16 13:36 UTC, drobnikj requested changes
Please add simple tests.
There is a skeleton prepared already.
https://github.com/apify/apify-client-js/blob/master/test/runs.test.js#L204

2021-06-18 08:47 UTC, nguyeda1 commented
Added the same tests as for `actor().lastRun()`

2021-06-18 08:47 UTC, nguyeda1 commented
> Please add simple tests.
> There is a skeleton prepared already.
> https://github.com/apify/apify-client-js/blob/master/test/runs.test.js#L204

Added the same tests as for actor().lastRun()

2021-06-21 14:58 UTC, drobnikj approved these changes

2021-06-21 15:13 UTC, merged