Add method to run webhook test
apify/apify-client-js pull request #181
Opened 2021-07-15 14:22 UTC by jirimoravcik

Add method to run webhook test;

Should this method be added to the python package? @drobnikj

2021-07-16 07:32 UTC, drobnikj requested changes
Please update the changelog and bump version, otherwise looks good.

2021-07-16 07:33 UTC, drobnikj commented
Plus check the linting check, it looks like it failed.

2021-07-16 07:34 UTC, drobnikj commented
> Should this method be added to the python package?

If you are about to add it you can, but we can leave it for @fnesveda.

2021-07-19 12:25 UTC, drobnikj approved these changes

2021-07-19 12:36 UTC, mnmkng requested changes

2021-07-19 12:36 UTC, mnmkng commented on CHANGELOG.md
> +
New method is a new feature so it should be a [semver-minor](https://semver.org/#spec-item-7) bump to `1.3.0`. Should've been done in earlier changes as well, but better late than never.

2021-07-20 09:09 UTC, mnmkng approved these changes

2021-07-20 09:10 UTC, merged