feat: add request queue requests list method
apify/apify-client-js pull request #249
Opened 2022-05-20 20:59 UTC by drobnikj

2022-06-02 07:13 UTC, mtrunkat approved these changes

2022-06-02 07:47 UTC, fnesveda requested changes
Nice! I love the async iterator over the items, that's something I'd like to have for all the `listSomething` methods in the client, like [OctoKit has it](https://github.com/octokit/plugin-paginate-rest.js/).

Just one idea - maybe it would be better to `yield` the requests from the `AsyncIterator` one by one, instead of as whole pages? That way you'd hide the whole pagination logic from the users completely, and they could just do:
```js
for await (const request of client.requestQueue(queueId).paginateRequests()) {
    // do something with `request`
}
```

I think it wouldn't be a big change, you could just do `yield* page.items` instead of `yield page`.

2022-06-02 07:47 UTC, fnesveda commented on src/resource_clients/request_queue.ts
> +    paginateRequests(options: RequestQueueClientRequestsOptions = {}): RequestQueueRequestsAsyncIterable<RequestQueueClientListRequestsResult> {
I think it should be like this:
```suggestion
    paginateRequests(options: RequestQueueClientPaginateRequestsOptions = {}): RequestQueueRequestsAsyncIterable<RequestQueueClientListRequestsResult> {
```

2022-06-02 15:39 UTC, drobnikj commented
> `yield` the requests from the `AsyncIterator` one by one

I had it like that originally, but I found out that with one by one you cannot easily call batch operations like batchDeleteRequests.

2022-06-03 11:39 UTC, mnmkng commented
Maybe it could be an option? `yieldRequests: true` or smth like that. I think both use-cases are valid.

2022-06-03 15:38 UTC, drobnikj commented
> Maybe it could be an option?

I would not overcomplicate now. I would say the main customer for this is SDK, so we can adjust if we found we need request by request during the implementation of rq2 into SDK.

2022-06-06 12:45 UTC, B4nan approved these changes
> so we can adjust if we found we need request by request during the implementation of rq2 into SDK.

I am aligned with this - let's improve when we see its needed.

2022-06-06 14:38 UTC, merged