feat: add support for `maxItems` in run options
apify/apify-client-js pull request #330
Opened 2023-03-07 13:19 UTC by novotnyj

This adds support for optional `maxItems` param to `start` and `call` methods on actors and tasks. 

This param will be used by pay per result actors to limit max items that will be charged to customer.

Should be merged after https://github.com/apify/apify-worker/pull/734 is released.

2023-03-07 16:25 UTC, mhamas requested changes

2023-03-07 16:25 UTC, mhamas commented on src/resource_clients/actor.ts
> +     * Specifies maximum number of items that the actor run should process.
should "return", not "process"

2023-03-07 16:25 UTC, mhamas commented on test/actors.test.js
> +            const maxItems = 100;
is there a unit test that also works without `maxItems`? To verify that this param is really optional.

2023-03-08 09:30 UTC, mhamas approved these changes

2023-03-09 09:51 UTC, vladfrangu approved these changes

2023-03-09 11:24 UTC, merged

2023-03-09 11:26 UTC, B4nan commented
> Should be merged after https://github.com/apify/apify-worker/pull/734 is released.

I hope it won't mind I merged this @novotnyj, will hold the stable release before that PR is merged.

2023-03-09 13:59 UTC, novotnyj commented
It's ok, it won't break anything🙂