feat: enable ApifyClient.builds() and runs()
apify/apify-client-js pull request #468
Opened 2023-12-06 15:45 UTC by foxt451

Closes #296

2024-02-05 12:38 UTC, B4nan commented
> @[drobnikj](https://github.com/drobnikj) drobnikj (Jakub Drobník) requested review from [B4nan](https://github.com/B4nan) and [drobnikj](https://github.com/drobnikj) 

This is not for our team to evaluate, I don't know the story behind it, nor the state of our API when it comes to supporting this.

2024-02-05 12:46 UTC, drobnikj requested changes
Thanks for pushing this forward. 
It looks good, can you please add unit tests for new methods?
You can check [here](https://github.com/apify/apify-client-js/pull/246/files#diff-ff1a96a183494b9c296289da90a1171bbc84c8e707c9e5ba5eda2aeac6b0b1fb) for example to have idea how to do it.

2024-02-05 12:46 UTC, drobnikj commented on src/apify_client.ts
> +    builds(): BuildCollectionClient {
Please add a reference to API docs into comments, the same as we had in the rest of the endpoints.

2024-02-05 12:46 UTC, drobnikj commented on src/apify_client.ts
> +    runs(): RunCollectionClient {
Same as the build list, please add a reference to docs.

2024-02-08 09:57 UTC, drobnikj approved these changes
👍

2024-02-08 10:22 UTC, B4nan commented
FYI I did some dependency updates including the shared eslint config, which now enforces import order, that's the reason for the conflicts. Those problems are autofixable.

2024-02-14 14:46 UTC, B4nan commented
I'd like to ship new minor version, would be good to include this there, @foxt451 can you please rebase and fix the linting issues?

2024-02-16 09:16 UTC, merged