Feat(client): Add maxCostPerRun param
apify/apify-client-js pull request #578
Opened 2024-08-16 13:04 UTC by stetizu1

Adds `maxCostPerRun` parameter to client - currently not doing anything, but not failing if it is received.

2024-08-16 14:01 UTC, mhamas approved these changes
Please, have @B4nan or somebody from his team to review as well. Thanks

2024-08-19 09:36 UTC, HonzaKirchner approved these changes

2024-08-19 13:42 UTC, barjin requested changes
I don't see anything wrong with the code, but I don't think we should merge this until it starts doing something :) Might be mighty confusing for users, despite the comment.

Any reason why you guys want this here this early?

2024-08-19 14:52 UTC, barjin commented
For bookkeeping: with @stetizu1 we agreed to modify only the `ow` validation and backend interaction while keeping the new parameter unlisted until it can be used by users.

2024-08-19 14:52 UTC, barjin approved these changes

2024-08-19 15:00 UTC, merged